### ISSUE TITLE
Save images locally

### ISSUE THREAD

**Issue by sangjunp4rk** [EllaToph/TeaCozy#3]
Try to save your images locally instead of adding a link. Saving images adds to the stability of your website because your website is not reliant on the link to be valid all the time. So next time, save all the images under resources/images/

https://github.com/EllaToph/TeaCozy/blob/master/index.html#L11

**Comment by EllaToph** [comment]
Oh ok! I had a images folder, but I deleted it because I thought it unnecessary. Only because I had the URL. Now I know and will be sure to do it next time.
